### ISSUE TITLE
Ensure Transmission/sonarr/radarr hardlinking works

### ISSUE THREAD

**Issue by coconutoil** [Ornias1993/jailman#67]
I haven't tested this yet but somethig I'm aware of with my current inefficient setup is that Sonarr can't hardlink properly (to save space), so as per this thread:

https://www.ixsystems.com/community/threads/iocage-hard-link-issues-with-radarr-and-sonarr.62356/

With this script putting downloads in its own dataset, will this be an issue?
And does the moving/hardlinking work as it is now?

**Comment by Ornias1993** [comment]
Thanks for reporting this.

Yes: hardlinking isn't supported at the moment thus Seeding isn't either (although might be possible with copy instead of move).

I also don't think I can make it work, as cross dataset hardlinking is problematic at best. certainly when jail 2 doesn't have access to both datasets jail 1 has. So unless someone PR's it or provides some clear design sketch about it (guide or something) this isn't....

So sadly enough I'll file this as "wontfix" and close the issue (as it's not within the design possibilities it seems).

**Comment by 1ccs-todd** [comment]
moving away from datasets for each media type would solve the issue.
just have the main media dataset and shows/movies/etc. as folders within.
keeping to one dataset allows hardlinks to work properly.

**Comment by Ornias1993** [comment]
I personally never had any interest in such a feature. Feel free to make a PR though...

I personally moved to scale, so at the moment this project is kinda frozen anyway...

**Comment by 1ccs-todd** [comment]
Make a PR to Master branch?
I cannot get the Dev branch to function at all.

**Comment by Ornias1993** [comment]
> Make a PR to Master branch?
> I cannot get the Dev branch to function at all.

Master branch PR's are not going to get merged. It's all dev branch for a while now (about 60% of the codebase is changed in the devbranch)
