### ISSUE TITLE
Support DHCP configured jails.

### ISSUE THREAD

**Issue by dak180** [Ornias1993/jailman#69]
This will at a minimum require setting the **vnet0_mac** and **dhcp**; additionally, to support _vlans_ this will also require being able to set the **interfaces**, **resolver**, **vnet_default_interface** and **vnet_interfaces**  including being able to set it explicitly to none. 

It may be easier to have a general method to set any given iocage property at jail creation time.

**Comment by Ornias1993** [comment]
VLAN and dhcp are already supported. 
I know because I use this daily using both.

>  to support vlans this will also require being able to set the interfaces, resolver, vnet_default_interface and vnet_interfaces including being able to set it explicitly to none.

I never required these to setup vlans in any way, shape or form. Except "interfaces" which is also already supported.

> It may be easier to have a general method to set any given iocage property at jail creation time.

In that case this project might not be for you.
It's designed do strike a balance between manual setup and plugins. Which means less options than manual but more options than plugins.

Considering both interfaces and dhcp are already supported in the config file, this is not a bug or an issue.

**Comment by dak180** [comment]
> VLAN and dhcp are already supported.
> I know because I use this daily using both.

Then consider this a documentation request because after looking through both the readme and the config example not only could I not figure out how to do it but I did not even realize it could be done.

To be clear and to make sure we are talking about the same thing; I would not consider dhcp fully supported unless you can specify the MAC address (so the jail can have a permanently assigned ip based on it) and for VLANs support it would need to accommodate VLANs other than what the main FreeNAS interface is on.

**Comment by Ornias1993** [comment]
> Then consider this a documentation request
use:
`dhcp: true` instead of setting an IP. There you go. Documented. 

> I would not consider dhcp fully supported unless you can specify the MAC address (so the jail can have a permanently assigned ip based on it)

Thats not part of dhcp, thats your personal preference.
DHCP is supported, manually setting MAC is not.

> for VLANs support it would need to accommodate VLANs other than what the main FreeNAS interface is on.

I personally use a setup similair to the guide by Lawrence Systems. I have no idea what you are talking about. If you have another setup you would like supported, feel free to PR it. But I personally do not consider it either supported or feature request worthy.

If this is about some sort of new IXsystems attempt of automated vlan-jail-setup: Their previous 99 attempts where either broken from the start or failed within about a year, so unless it keeps working for about a year i'm not interested in even trying it out.

**Comment by Ornias1993** [comment]
I've created a general issue convering the general lack of config-file parameter documentation.

Anyhow:
- There is no connection between VLANS and DHCP
- There is no NEED for custom mac support for DHCP
- Both DHCP and Interfaces are already supported
- Interfaces is even included in the default config example
- VLANS are supported, using the guide from Lawrence Systems (and others)

There might be more ways to setup VLANS. 

You wrote so many things unrelated to each other, or things that should be seperate issues. It gets very confusing.

So please feel free to open issue for seperate features you want included or things that are badly documented. Try and not create these big "wishlist" issues.

**Comment by Ornias1993** [comment]
Update:
Some of the requested documentation has just been uploaded as a PR:
https://github.com/Ornias1993/jailman/pull/76

**Comment by Ornias1993** [comment]
Extra documentation has been pushed before 1.2.0 to the new wiki, as requested.
